### ISSUE TITLE
[Bug] No git :( [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Kristinita** [max-mykhailenko/memTask#19]
Если не возражаете, буду писать на русском.
### Итог

Заметил, что у меня в консоли Sublime Text постоянно появляется следующая ошибка:

```
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'
```
### Желаемое поведение

Отсутствие ошибок в консоли.
### Актуальное поведение

Ошибка появляется в самые разные моменты. Примеры:

```
key evt: alt+keypad6
chr evt: → (0x2192)
chr evt:   (0x20)
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'

No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'
command: post_or_update_issue {}
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: api.github.com

key evt: shift+control+p
command: show_overlay {"overlay": "command_palette"}
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'

key evt: backspace
command: left_delete
chr evt:   (0x20)
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'
chr evt: в (0x432)
chr evt:   (0x20)

chr evt: I (0x49)
chr evt:   (0x20)
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'
chr evt: o (0x6f)

key evt: control+p
command: show_overlay {"overlay": "goto", "show_files": true}
chr evt: T (0x54)
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'
chr evt: e (0x65)
```
### Конфигурация

Мой сайдбар.

![Мой сайдбар](http://i.imgur.com/RuLbkZQ.png)

`Грейс Ло`, равно как и остальные папки в моём сайдбаре кроме двух, — это не папки локального git-репозитория.
### Шаги для воспроизведения

Проблема воспроизводится у меня на «чистой» версии Sublime Text без установленных плагинов и пользовательских настроек.

Постоянно появляется данная ошибка при различных действиях с моей стороны. Вычисляя, какой плагин мог вызвать подобное поведение, я обнаружил, что ошибка не появляется, если я деактивирую memTask и появляется, если я активирую этот плагин вновь.
### Программно-аппаратное окружение

**Операционная система**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Спасибо.

**Comment by max-mykhailenko** [comment]
Скорее всего в системе действительно нету git. Сделаю условие чтобы этот функционал git не использовался при его отсутствии.

**Comment by Kristinita** [comment]
@max-mykhailenko, в системе есть git. Но он инициализирован только в двух папках моего сайдбара. Не самой верхней. 

Спасибо.

**Comment by Kristinita** [comment]
Актуально в 2017.

Спасибо.

**Comment by Kristinita** [comment]
Проблема воспроизводится на Windows 64-bit EN LTSB.

Спасибо.

**Comment by max-mykhailenko** [comment]
Исправлено в версии 0.2.3. Проверьте, пожалуйста.
